version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
  app1:
    environment:
      - appName=app1
    build: .
    ports:
      - "3001:3000"
  app2:
    environment:
      - appName=app2
    build: .
    ports:
      - "3002:3000"
  app3:
    environment:
      - appName=app3
    build: .
    ports:
      - "3003:3000"
